site_name: NSI Claveille
site_description: Cours de NSI en première 
docs_dir: docs


theme:
  name: material
  font : false
  logo: assets/image/logoNSI.png
  palette:
    primary: indigo
  language : fr
  features:
    - header.autohide
  disable_nav_previous_next: true
  disable_nav_search: true



nav:
    - Home: index.md
    - Langages et programmation :
        - 'Les bases du langage Python': './1_Langage et programmation/Base_python.md'
        - "Les intéractions avec l'utilisateur": './1_Langage et programmation/Interactions_utilisateur.md'
        - 'Les fonctions' : './1_Langage et programmation/fonctions.md'
        - 'Les listes' : './1_Langage et programmation/listes/listes.md'
        - 'Construction de listes' : './1_Langage et programmation/listes/Construction_listes.md'
        - 'Les chaînes de caractères' : './1_Langage et programmation/chainesCaracteres.md'
    - Représentation de l'information :
      - 'Représentation des entiers positifs' : './2_Representation_information/entiers_positifs.md'

    - Annales d'épreuve de spécialité :
      - "Règlement des épreuves de terminale" : './10_Annales_EP/reglement.md'
      - 'Annales des épreuves pratiques' : './10_Annales_EP/EP2022/EP_NSI_2022.md'
extra:
    social:
       
      - icon: fontawesome/solid/paper-plane
        link: mailto:herve.drougard@ac-bordeaux.fr
        name: Écrire à l'auteur

      - icon: fontawesome/brands/github
        link: https://github.com/RVDROU
        name: Dépôt git

      - icon: fontawesome/solid/university
        link: http://claveille.org/
        name: Lycée Albert Claveille - Périgueux -

extra_javascript:
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js



markdown_extensions:
    - md_in_html
    - meta
    - abbr
    - def_list                      # Les listes de définition.
    - attr_list                     # Un peu de CSS et des attributs HTML.
    - footnotes                     # Notes[^1] de bas de page.  [^1]: ma note.
    - admonition                    # Blocs colorés  !!! info "ma remarque"
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.details              #   qui peuvent se plier/déplier.
    - pymdownx.caret                # Passage ^^souligné^^ ou en ^exposant^.
    - pymdownx.mark                 # Passage ==surligné==.
    - pymdownx.tilde                # Passage ~~barré~~ ou en ~indice~.
    - pymdownx.highlight            # Coloration syntaxique du code
    - pymdownx.superfences
    - pymdownx.inlinehilite         # pour  `#!python  <python en ligne>`
    - pymdownx.snippets             # Inclusion de fichiers externe.
    - pymdownx.tasklist:            # Cases à cocher  - [ ]  et - [x]
        custom_checkbox:    false   #   avec cases d'origine
        clickable_checkbox: true    #   et cliquables.
    - pymdownx.tabbed               # Volets glissants.  === "Mon volet"
    - pymdownx.superfences          # Imbrication de blocs.
    

  