site_name: NSI Claveille
site_description: Cours de NSI en première 
docs_dir: docs


theme:
  name: null
  custom_dir: 'cinder'
  colorscheme: dracula
  disable_nav_previous_next: true
  disable_nav_search: true
  highlightjs: true
  hljs_languages:
    - Python



nav:
    - Home: index.md
    - Langages et programmation :
        - 'Les bases du langage Python': './1_Langage et programmation/Base_python.md'
        - "Les intéractions avec l'utilisateur": './1_Langage et programmation/Interactions_utilisateur.md'
        - 'Les listes' : './1_Langage et programmation/listes/listes.md'
        - 'Construction de listes' : './1_Langage et programmation/listes/Construction_listes.md'
        - 'Les chaînes de caractères' : './1_Langage et programmation/chainesCaracteres.md'


markdown_extensions:
  - admonition